// <auto-generated />
using DogBarberShop.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DogBarberShop.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("DogBarberShop.Models.QueueData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreateAt")
                        .HasColumnType("longtext");

                    b.Property<string>("TimeOfTheQueue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Queue");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = "2021-07-26T22:08",
                            TimeOfTheQueue = "2021-07-26T22:08",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = "2021-07-26T22:08",
                            TimeOfTheQueue = "2021-07-26T22:08",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = "2021-07-26T22:08",
                            TimeOfTheQueue = "2021-07-26T22:08",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = "2021-07-26T22:08",
                            TimeOfTheQueue = "2021-07-26T22:08",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("DogBarberShop.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Name = "iman",
                            Password = "1234",
                            UserName = "shuk"
                        },
                        new
                        {
                            UserId = 2,
                            Name = "Alex",
                            Password = "1234",
                            UserName = "csc"
                        },
                        new
                        {
                            UserId = 3,
                            Name = "gabi",
                            Password = "1234",
                            UserName = "asww"
                        },
                        new
                        {
                            UserId = 4,
                            Name = "mishel",
                            Password = "1234",
                            UserName = "wer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
